spring:
  app:
    credentials:
      username: admin
      passcode: Denom@007

  application:
    name: my-application

  datasource:
    url: jdbc:mysql://localhost:3306/SRMS
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true